[package]
name = "xtask"
version.workspace = true
edition.workspace = true

[dependencies]
tracel-xtask = { version = "=5.0.0", features = ["build", "bump", "check", "compile", "doc", "fix", "publish", "test", "validate", "utils-time"] }
log = "0.4.33"
strum = { version = "0.27.2", features = ["derive"] }
